---
title: "rawdata input and cleaning"
author: "MPG"
date: "April 5, 2019"
output: html_document
---
data input from .csv and RESEARCH server
file is named by sensor's name only. File include date,time,battery,temperature,chl(ug/L),gain voltage
remember to change chl column from scientific format to general
```{r setup, include=FALSE}
setwd("R:/EcosystemsLab/Ecosystems projects/Brandywine/working_data/sensors/cyclops")
chldata = read.csv("BRA_WILMA.csv") ; chldata[,1] <- NULL ; tail(chldata,1)
chldata2 = read.csv("BRA_WILMA_June6-June202019.csv") ; head(chldata2,1)
chldata = rbind(chldata,chldata2)
write.csv(chldata, file = "BRA_WILMA.csv")

qdata <- read.csv(url("https://waterdata.usgs.gov/nwis/dv?cb_00010=on&cb_00045=on&cb_00060=on&cb_00095=on&cb_00300=on&cb_00400=on&cb_63680=on&cb_80154=on&cb_80155=on&format=rdb&site_no=01481000&referred_module=sw&period=&begin_date=2018-03-27&end_date=2019-04-04.txt"))
qdata = read.csv("qdata.csv") 
```  

Package loads
```{r,warning=F}
#necessary packages: 
pack_list<-list ("ggplot2","openair","dygraphs","xts")
for(i in 1:length(pack_list)){
  install.packages(paste("", pack_list[[i]]),repos = "http://cran.us.r-project.org")
}

```

Calculate daily means/max/min from high-frequency data
```{r}
date<-as.Date(chldata$date, format = "%m/%d/%Y")
date<-as.POSIXlt(date, tz = "America/New_York")

mean_daily_chl<-aggregate(chl ~ date, data = chldata, mean)
max_daily_chl<-aggregate(chl ~ date, data = chldata, max)
min_daily_chl<-aggregate(chl ~ date, data = chldata, min)
range_daily_chl<-aggregate(chl ~ date, data = chldata, range)

```

Seston Chlorophyll time series------using dygraphs interactive: https://www.r-graph-gallery.com/time-series/
```{r}
library(dygraphs);library(xts)
chl_series=cbind(mean_daily_chl,max_daily_chl[,2],min_daily_chl[,2])
colnames(chl_series)<-c("date","mean","max","min")
chl_series$date<-as.Date(chl_series$date, format = "%m/%d/%Y") #output is YYY-mm-dd
timeseries_chl=xts(x = chl_series[,-1], order.by = chl_series$date)
 
dygraph(timeseries_chl,xlab = NULL, ylab = "sestonic chl (ug/L)") %>%
  dySeries(c("min", "mean", "max"))
```

Q-chl rating curve
```{r}
library(ggplot2)
ratingcurve<-merge(mean_daily_chl,qdata,by = c("date"))

ggplot(ratingcurve, aes(x=Discharge, y=chl)) +
    geom_point(shape=1,size=3) +    
    geom_smooth(method=lm) +
    xlab("discharge (feet3/s)") +
    ylab("sestonic chl (ug/L)") +
    theme_bw()
```

