---
title: "StormEventAnalysis"
author: "MPG"
date: "9/25/2020"
output: html_document
---

*Hysteresis indices per event*
Calculates Hysteresis Index (HI) and Flushing Index (FI) for both Chlorophyll and Turbidity
```{r setup, include=FALSE}
library (ggplot2) ; library(lubridate) ; library(dplyr) ; library(zoo) ; library(RColorBrewer) ; library(gridExtra) ; library(DescTools)
setwd("C:/Users/mpeipoch/Dropbox/manuscripts/RiverPlankton/working_files/stormfiles")
```

```{r}
file.names <- dir(getwd(), pattern =".csv") 
df<-data.frame(matrix(ncol = 9, nrow = 0)) 
colnames(df) <- c("date","HI_chl","FI_chl","HI_turb","FI_turb","Qmax","Qmin","Chlmax","Turbmax") #name for the nine vars: date_storm,HI_chl, FI_chl, HI_tur, FI_tur, Qmax, Qmin, Chlmax, Turbmax

for(i in 1:length(file.names)){  
              
         date_storm = file.names[i]
         file <- read.table(file.names[i],header=TRUE, sep=",", stringsAsFactors=TRUE)
           raw_data <- file

#extract min/max values and first value for Q, Chl, and Turb 
Qmax = max(raw_data$Q) ; Qmin = min(raw_data$Q) ; Qfirst = raw_data[1,2]
Chlmax = max(raw_data$Chl) ; Chlmin = min(raw_data$Chl)
Turbmax = max(raw_data$Turb) ; Turbmin = min(raw_data$Turb)
Chlmedian = median(raw_data$Chl)
Turbmedian = median(raw_data$Turb)


norm_data = raw_data #end for raw_data
#normalize Q, Chl, and Turb
norm_data$Q_norm = 
  (norm_data$Q - Qmin)/(Qmax - Qmin)
norm_data$Chlorophyll_norm = 
  (norm_data$Chl - Chlmin)/(Chlmax - Chlmin)
norm_data$Turbidity_norm = 
  (norm_data$Turb - Turbmin)/(Turbmax - Turbmin)

a = rep("rising",max(which(norm_data$Q == Qmax)))  #mark rising cases
b = rep("falling",nrow(norm_data) - max(which(norm_data$Q == Qmax))) #rest are falling
norm_data$limb = c(a,b) #create a limb factor

#Find pairs of Q-norm and C-norm at 1% intervals in the RISING LIMB---------------------------------rising limb

rise_data  = norm_data %>%
  filter(., limb == "rising") %>%
  select(!(Turb:Temp)) %>%
  group_by(Q_norm) %>%
  summarise(chl.avg = mean(Chlorophyll_norm, na.rm = TRUE), 
            turb.avg = mean(Turbidity_norm, na.rm = TRUE)) 
 
rise_data = as.data.frame(rise_data) # remove tibble info

rise_Chl_interpolated = as.data.frame(approx(rise_data$Q_norm, rise_data$chl.avg,method = "linear", n = 100))
colnames(rise_Chl_interpolated) <- c("Qnorm", "Chlnorm") #for chlorophyll
rise_Chl_interpolated = round(rise_Chl_interpolated,2)

rise_Turb_interpolated = as.data.frame(approx(rise_data$Q_norm, rise_data$turb.avg, method = "linear", n = 100))
colnames(rise_Turb_interpolated) <- c("Qnorm", "Turbnorm") #for Turbidity
rise_Turb_interpolated = round(rise_Turb_interpolated,2)

#Find pairs of Q-norm and C-norm at 1% intervals in the FALLING LIMB---------------------------------falling limb

fall_data  = norm_data %>%
  filter(., limb == "falling") %>%
  select(!(Turb:Temp)) %>%
  group_by(Q_norm) %>%
  summarise(chl.avg = mean(Chlorophyll_norm, na.rm = TRUE), 
            turb.avg = mean(Turbidity_norm, na.rm = TRUE)) 
 
fall_data = as.data.frame(fall_data) # remove tibble info

fall_Chl_interpolated = as.data.frame(approx(fall_data$Q_norm, fall_data$chl.avg,method = "linear", n = 100))
colnames(fall_Chl_interpolated) <- c("Qnorm", "Chlnorm") #for chlorophyll
fall_Chl_interpolated = round(fall_Chl_interpolated,2)

fall_Turb_interpolated = as.data.frame(approx(fall_data$Q_norm, fall_data$turb.avg, method = "linear", n = 100))
colnames(fall_Turb_interpolated) <- c("Qnorm", "Turbnorm") #for Turbidity
fall_Turb_interpolated = round(fall_Turb_interpolated,2)

#merge and calculate HIs
#----Chl----------
merged_Chl_data = inner_join(rise_Chl_interpolated,fall_Chl_interpolated, by = "Qnorm")
merged_Chl_data$HI = merged_Chl_data$Chlnorm.x - merged_Chl_data$Chlnorm.y

#------Turb-------
merged_Turb_data = inner_join(rise_Turb_interpolated,fall_Turb_interpolated, by = "Qnorm")
merged_Turb_data$HI = merged_Turb_data$Turbnorm.x - merged_Turb_data$Turbnorm.y


#calculate final parameters for CHLOROPHYLL AND TURBIDITY and put them in a table
HI_chl = mean(merged_Chl_data$HI)
HI_tur = mean(merged_Turb_data$HI)

FI_chl = mean(norm_data[which(norm_data$Q == Qmax), "Chlorophyll_norm"]) - 
            mean(norm_data[1:3, "Chlorophyll_norm"]) 

FI_tur = mean(norm_data[which(norm_data$Q == Qmax), "Turbidity_norm"]) - 
            mean(norm_data[1:3, "Turbidity_norm"])


results <- list(date_storm,HI_chl, FI_chl, HI_tur, FI_tur, Qmax, Qmin, Chlmax, Chlmin)
results = as.data.frame(as.vector(results))
colnames(results) <- c("date","HI_chl","FI_chl","HI_turb","FI_turb","Qmax","Qmin","Chlmax","Chlmin") 
df<-rbind(df,results)

}


write.csv(df,file = "C:/Users/mpeipoch/Dropbox/manuscripts/RiverPlankton/working_files/StormIndices.csv") #
```


*Hysteresis indices per event*
```{r setup, include=FALSE}
library (ggplot2) ; library(lubridate) ; library(dplyr) ; library(zoo) ; library(RColorBrewer) ; library(gridExtra)
setwd("C:/Users/mpeipoch/Dropbox/manuscripts/RiverPlankton/working_files/stormfiles")
raw_data <- read.csv("BAM_A_1Apr2019.csv",head=T,sep=",") # load storm event file data

#upper boundary of Stromflow observations
up_Storm = min(which(raw_data[,"FlowType"] == "Stormflow")) 
#lower boundary of Stromflow observations
dw_Storm = max(which(raw_data[,"FlowType"] == "Stormflow")) 

storm_data = raw_data[(up_Storm:dw_Storm),] #selecting 20 observation above and below the Storm hydrograph
storm_data$date = as.Date(storm_data$date, "%m/%d/%Y") #convert date as character into a class 'Date' column that lubridate recognizes 
storm_data$datetime = with(storm_data, ymd(date) + hms(time)) #create a variable with datetime using lubridate

plot_storm_data = storm_data %>% 
  mutate(chl.hour = rollmean(x = Chl, 4, align = "right", fill = NA)) %>% 
  mutate(Turbidity.hour = rollmean(x = Turbidity, 4, align = "right", fill = NA))

p = ggplot(plot_storm_data, aes(Discharge, chl.hour)) +
  geom_point(aes(colour = datetime), size = 2) + 
  geom_path(aes(colour = datetime), size = 1) + 
  theme_light()

q= ggplot(plot_storm_data, aes(Discharge, Turbidity.hour)) +
  geom_point(aes(colour = datetime), size = 2) + 
  geom_path(aes(colour = datetime), size = 1) + 
  theme_light()

grid.arrange(p,q,ncol=1)

```



